version: '3.11'
services:
  web:
    image: newspaper
    container_name: web
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=newspaper
      - POSTGRES_USER=rest
      - POSTGRES_PASSWORD=rest

volumes:
  db_data:
